# Generated by Django 4.2.23 on 2025-08-21 22:32
# This file was automatically generated by Django's 'makemigrations' command
# It represents a snapshot of the models.py file at a specific point in time
# Django uses these files to create + update the database schema

# Import necessary modules from Django for migrations + model field definitions
from django.db import migrations, models
import django.db.models.deletion
import uuid

# Each migration is a class that inherits from migrations.Migration
class Migration(migrations.Migration):

    # This flag indicates that it's the first migration for this app
    initial = True

    # This list specifies any other migrations that must be run before this one
    # It's empty because this is the very first migration
    dependencies = [
    ]

    # The 'operations' list contains the set of instructions for the database.
    # Django will execute these operations in order when the 'migrate' command is run
    operations = [
        # This operation tells the database to create a new table named 'shop_cart'
        migrations.CreateModel(
            name='Cart',
            fields=[
                # Define the columns for the 'shop_cart' table
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # This operation creates the 'shop_product' table
        migrations.CreateModel(
            name='Product',
            fields=[
                # Define the columns for the 'shop_product' table
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(max_length=1024)),
                ('category', models.CharField(choices=[('preteen', 'Preteen'), ('teen', 'Teen')], max_length=50)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('sub_category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', max_length=50)),
            ],
        ),
        # This operation creates the 'shop_cartitem' table
        migrations.CreateModel(
            name='CartItem',
            fields=[
                # Define the columns for the 'shop_cartitem' table
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
