# Generated by Django 4.2.23 on 2025-08-22 23:07
# This file was automatically generated by Django's 'makemigrations' command
# It contains the instructions to add the Order + OrderItem models to the database

# Import necessary modules from Django for migrations and model field definitions
from django.db import migrations, models
import django.db.models.deletion

# The main migration class
class Migration(migrations.Migration):

    # This list specifies that this migration depends on the '0001_initial' migration
    # This ensures that the 'Product' table exists before we try to create an OrderItem that links to it
    dependencies = [
        ('shop', '0001_initial'),
    ]

    # The list of database operations to perform
    operations = [
        # This operation creates the 'shop_order' table
        migrations.CreateModel(
            name='Order',
            fields=[
                # Define the columns for the 'shop_order' table
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        # This operation creates the 'shop_orderitem' table
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                # Define the columns for the 'shop_orderitem' table
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
