# Generated by Django 4.2.23 on 2025-08-22 23:45
# This file was automatically generated by Django's 'makemigrations' command.
# It contains the instructions to add the optional 'user' field to the 'Order' model

# Import necessary modules from Django for migrations + model field definitions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# The main migration class
class Migration(migrations.Migration):

    # This list specifies that this migration has two dependencies
    dependencies = [
        # This is a SPECIAL dependency that ensures Django's built-in User model table exists
        # before we try to create a field that links to it
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

        # This ensures that the '0002_order_orderitem' migration has run first,
        # so the 'Order' table exists before we try to add a field to it
        ('shop', '0002_order_orderitem'),
    ]

    # The list of database operations to perform
    operations = [
        # This operation doesn't create a new table, but instead adds a new field (column) to an existing model (table)
        migrations.AddField(
            model_name='order', # The model to modify
            name='user', # The name of the new field to add
            
             # The definition of the new field, creating an optional foreign key relationship to the built-in User model
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
