# Generated by Django 4.2.23 on 2025-08-24 16:13
# This file was automatically generated by Django's 'makemigrations' command
# It contains the instructions to add the optional 'model_image_url' field to the 'Product' model

# Import necessary modules from Django for migrations + model field definitions
from django.db import migrations, models

# The main migration class
class Migration(migrations.Migration):

    # This list specifies that this migration depends on the '0003_order_user' migration
    # This ensures all previous migrations have been run in the correct order
    dependencies = [
        ('shop', '0003_order_user'),
    ]

    # The list of database operations to perform
    operations = [
        # This operation adds a new field (column) to an existing model (table)
        migrations.AddField(
            model_name='product', # The model to modify
            name='model_image_url', # The name of the new field to add

             # The definition of the new field
             # It's an optional CharField to store the second image URL for the hover effect
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
