# Generated by Django 4.2.23 on 2025-08-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
