# Generated by Django 4.2.23 on 2025-08-24 17:39
# This file was automatically generated by Django's 'makemigrations' command
# It contains the instructions to change the available 'choices' for the sub_category field

# Import necessary modules from Django
from django.db import migrations, models

# The main migration class
class Migration(migrations.Migration):

    # This specifies that this migration must be run after the '0004_product_model_image_url' migration
    dependencies = [
        ('shop', '0004_product_model_image_url'),
    ]

    # The list of database operations to perform
    operations = [
        # This operation alters an existing field on a model
        migrations.AlterField(
            model_name='product', # The model to modify
            name='sub_category', # The name of the field to change

            # The new definition for the field, which now includes updated 'choices'
            # for the dropdown menu in the Django Admin
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('sets', 'Sets')], default='tops', max_length=50),
        ),
    ]
