# Generated by Django 4.2.23 on 2025-08-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charity_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
